/* 
 * File:   mcal_usart_cfg.h
 * Author: nour
 *
 * Created on August 22, 2025, 7:56 PM
 * @brief: This file contains pre-configuration for the USART module.
 */

#ifndef HAL_USART_CFG_H
#define	HAL_USART_CFG_H

#define USART_MODULE STD_OFF
#define _ASYNC 0 
#define _SYNC_MASTER 1 
#define _SYNC_SLAVE 2
#define _OFF 3
#define _ON 4
#define DIS 0
#define EN 1

/* The USART module can work in three different modes: 
 * asynchronous, master synchronous, and slave synchronous. 
 *
 * The hardware for the transmitter and receiver is separated. 
 *
 * In master synchronous mode, the clock is generated by the 
 * transmitter/receiver. In this mode, RC6 is the clock (CK) line 
 * while RC7 is the data line (DT).
 *
 * The hardware allows 9th bit both to use as a data bit or as a parity bit.
 * Below are macros to choose the operating mode, the use of a 9th bit for data, and 
 * the use for the 9th bit for parity 
 */
#define USART_MODE _SYNC_MASTER
#define USART_PARITY _ON
#define _9BIT DIS 



#endif	/* HAL_USART_CFG_H */

